name: Update README with Current Date

on:
  # Run the workflow every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  # Run the workflow when there's a push to the main branch
  push:
    branches:
      - main
  # Allow the workflow to run manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update README with the current date
        run: |
          DATE=$(date +"%A, %B %d, %Y %H:%M:%S")
          sed -i "s/<!--DATE_PLACEHOLDER-->/$DATE/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with current date"
          git push
